# 指定构建的语言
language: node_js

# 指定node为稳定版本
node_js: stable

# 需要使用sudo权限
sudo: required

# 设置缓存文件
cache:
  directories:
  - node_modules

# githubio下的源码分支
branches:
  only:
  - feature/writing

# 在构建之前安装hexo环境
before_install:
- npm install -g hexo-cli

# 启动hexo并构建生命周期
install:
- npm install
- npm install hexo-deployer-git --save

# 执行构建部署
script:
- hexo clean
- hexo generate

# 设置git提交名，邮箱；替换真实token到_config.yml文件
after_script:
- git config user.name "xiaokunliu"
- git config user.email "liuxkmail@gmail.com"
- sed -i "s/github_token/${GITHUB_TOKEN}/g" _config.yml
- hexo deploy
