## 基于Travis CI自动构建


# 指定构建环境是Node.js，当前版本是稳定版
anguage: node_js
node_js: stable

env:
  global:
  - URL_REPO: github.com/xiaokunliu/xiaokunliu.github.io.git

# 设置钩子只检测blog-source分支的push变动
branches:
  only:
  - hexo

# 设置缓存文件
cache:
  directories:
  - node_modules

#在构建之前安装hexo环境
before_install:
- npm install -g hexo-cli

#安装git插件和搜索功能插件
install:
- npm install

# 设置git提交名，邮箱；替换真实token到_config.yml文件
before_script:
- git config user.name "xiaokunliu"
- git config user.email "liuxkmail@gmail.com"

# 替换同目录下的_config.yml文件中github_token字符串为travis后台刚才配置的变量，注>意此处sed命令用了双引号。单引号无效！
- sed -i "s/github_token/${GH_TOKEN}/g" _config.yml || exit 1

# 执行清缓存，生成网页操作
script:
- hexo clean
- hexo generate
- echo ${ENV_TEST}
- hexo deploy

# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
# https://docs.travis-ci.com/user/notifications/
notifications:
  email:
  - 1248237617@qq.com
  - liuxkmail@gmail.com
  on_success: change
  on_failure: always
